import { QueryClient,QueryClientProvider } from '@tanstack/react-query'; import { ConfigProvider,Modal,message } from 'antd'; import viVN from 'antd/locale/vi_VN'; import { act,fireEvent,render,screen,waitFor,within } from '@testing-library/react'; import userEvent from '@testing-library/user-event'; import { MemoryRouter } from 'react-router-dom'; import { afterEach,beforeEach,describe,expect,it,vi } from 'vitest';
import * as apiModule from '../../../../api/craft-villages'; import { useAuthStore } from '../../../../store/auth-store'; import type { CraftVillageAdminItem } from '../../../../types/craft-village'; import { CraftVillagesPage } from '../CraftVillagesPage';
vi.mock('../../../../api/craft-villages');const api=vi.mocked(apiModule);const admin={id:'admin',zaloId:null,phone:null,email:null,displayName:'Admin',avatarUrl:null,role:'ADMIN' as const,status:'ACTIVE' as const,lastLoginAt:null,createdAt:'',updatedAt:''};
function item(overrides:Partial<CraftVillageAdminItem>={}):CraftVillageAdminItem{return{id:'pottery',version:2,name:'Làng gốm LocalGo',category:'Thủ công truyền thống',address:'Bình Dương',workingTime:'08:00 - 17:00',mainProducts:'Gốm thủ công',summary:'Làng nghề truyền thống',description:['Đoạn giới thiệu'],highlights:[],visitorNote:'',mediaId:'media-1',imageUrl:'https://cdn/pottery.webp',imageAlt:'Nghệ nhân làm gốm',sortOrder:0,isActive:true,updatedAt:'2026-07-15T00:00:00.000Z',updatedBy:null,...overrides};}
function renderPage(){const client=new QueryClient({defaultOptions:{queries:{retry:false},mutations:{retry:false}}});return render(<QueryClientProvider client={client}><ConfigProvider locale={viVN}><MemoryRouter><CraftVillagesPage/></MemoryRouter></ConfigProvider></QueryClientProvider>);}
beforeEach(()=>{useAuthStore.setState({user:admin});api.fetchCraftVillages.mockResolvedValue({data:[item()],meta:{page:1,limit:20,total:1,totalPages:1}});});afterEach(()=>{vi.clearAllMocks();useAuthStore.setState({user:null});act(()=>{message.destroy();Modal.destroyAll();});});
describe('CraftVillagesPage',()=>{
  it('renders and sends category and search filters',async()=>{renderPage();const user=userEvent.setup({delay:null,pointerEventsCheck:0});expect(await screen.findByText('Làng gốm LocalGo')).toBeInTheDocument();expect(screen.getByText('Tổng cộng 1 mục, bao gồm cả đang ẩn.')).toBeInTheDocument();fireEvent.mouseDown(screen.getByText('Tất cả danh mục'));fireEvent.click(await screen.findByTitle('Chế biến nông sản'));await waitFor(()=>expect(api.fetchCraftVillages).toHaveBeenLastCalledWith(expect.objectContaining({category:'Chế biến nông sản'}),expect.anything()));await user.type(screen.getByPlaceholderText('Tìm theo tên hoặc địa chỉ'),'Bình Dương{Enter}');await waitFor(()=>expect(api.fetchCraftVillages).toHaveBeenLastCalledWith(expect.objectContaining({search:'Bình Dương',page:1}),expect.anything()));});
  it('toggles status with version then refreshes',async()=>{const row=item();api.updateCraftVillageStatus.mockResolvedValue({...row,isActive:false,version:3});renderPage();const user=userEvent.setup({delay:null});await screen.findByText(row.name);await user.click(screen.getByRole('switch'));await waitFor(()=>expect(api.updateCraftVillageStatus).toHaveBeenCalledWith(row.id,false,row.version));await waitFor(()=>expect(api.fetchCraftVillages).toHaveBeenCalledTimes(2));});
  it('normalizes reorder positions',async()=>{const first=item({id:'a',name:'Làng A',sortOrder:8});const second=item({id:'b',name:'Làng B',sortOrder:10});api.fetchCraftVillages.mockResolvedValue({data:[first,second],meta:{page:1,limit:20,total:2,totalPages:1}});api.reorderCraftVillages.mockResolvedValue([second,first]);renderPage();const user=userEvent.setup({delay:null});await screen.findByText(first.name);await user.click(screen.getAllByRole('button',{name:'Đưa xuống'})[0]);await waitFor(()=>expect(api.reorderCraftVillages).toHaveBeenCalled());expect(api.reorderCraftVillages.mock.calls[0][0]).toEqual([{id:'b',sortOrder:0},{id:'a',sortOrder:1}]);});
  it('deletes once after confirmation',async()=>{api.deleteCraftVillage.mockResolvedValue(undefined);renderPage();const user=userEvent.setup({delay:null,pointerEventsCheck:0});await screen.findByText('Làng gốm LocalGo');await user.click(screen.getByRole('button',{name:'Xóa'}));const dialog=await screen.findByRole('dialog');const confirm=within(dialog).getByRole('button',{name:'Xóa'});fireEvent.click(confirm);fireEvent.click(confirm);await waitFor(()=>expect(api.deleteCraftVillage).toHaveBeenCalledTimes(1));});
  it('is read-only for moderators',async()=>{useAuthStore.setState({user:{...admin,role:'MODERATOR'}});renderPage();await screen.findByText('Làng gốm LocalGo');expect(screen.getByText('Bạn đang xem ở chế độ chỉ đọc')).toBeInTheDocument();expect(screen.getByRole('switch')).toBeDisabled();expect(screen.queryByRole('button',{name:/Thêm mục mới/})).not.toBeInTheDocument();expect(within(screen.getByRole('table')).queryByRole('button',{name:'Xóa'})).not.toBeInTheDocument();});
});
