import { QueryClient,QueryClientProvider } from '@tanstack/react-query'; import { ConfigProvider,Modal,message } from 'antd'; import viVN from 'antd/locale/vi_VN'; import { act,fireEvent,render,screen,waitFor } from '@testing-library/react'; import userEvent from '@testing-library/user-event'; import { MemoryRouter,Route,Routes } from 'react-router-dom'; import { afterEach,beforeEach,describe,expect,it,vi } from 'vitest';
import * as apiModule from '../../../../api/craft-villages'; import { useAuthStore } from '../../../../store/auth-store'; import { ApiError } from '../../../../types/api'; import type { CraftVillageAdminItem } from '../../../../types/craft-village'; import { CraftVillageFormPage } from '../CraftVillageFormPage';
vi.mock('../../../../api/craft-villages');vi.mock('../../about/ImageUploadField',()=>({ImageUploadField:()=> <div data-testid="image-upload">Ảnh đã chọn</div>}));const api=vi.mocked(apiModule);
const admin={id:'admin',zaloId:null,phone:null,email:null,displayName:'Admin',avatarUrl:null,role:'ADMIN' as const,status:'ACTIVE' as const,lastLoginAt:null,createdAt:'',updatedAt:''};
const item:CraftVillageAdminItem={id:'pottery',version:2,name:'Làng gốm LocalGo',category:'Thủ công truyền thống',address:'Bình Dương',workingTime:'08:00 - 17:00',mainProducts:'Gốm thủ công',summary:'Làng nghề truyền thống',description:['Đoạn giới thiệu'],highlights:['Nghệ nhân lâu năm'],visitorNote:'Đặt lịch trước',mediaId:'media-1',imageUrl:'https://cdn/pottery.webp',imageAlt:'Nghệ nhân làm gốm',sortOrder:0,isActive:true,updatedAt:'2026-07-15T00:00:00.000Z',updatedBy:null};
function renderForm(){const client=new QueryClient({defaultOptions:{queries:{retry:false},mutations:{retry:false}}});return render(<QueryClientProvider client={client}><ConfigProvider locale={viVN}><MemoryRouter initialEntries={['/content/craft-villages/pottery']}><Routes><Route path="/content/craft-villages/:id" element={<CraftVillageFormPage/>}/><Route path="/content/craft-villages" element={<div>Danh sách</div>}/></Routes></MemoryRouter></ConfigProvider></QueryClientProvider>);}
beforeEach(()=>{useAuthStore.setState({user:admin});api.fetchCraftVillage.mockResolvedValue(item);});afterEach(()=>{vi.clearAllMocks();useAuthStore.setState({user:null});act(()=>{message.destroy();Modal.destroyAll();});});
describe('CraftVillageFormPage',()=>{
  it('updates with trimmed data and current version',async()=>{api.updateCraftVillage.mockResolvedValue({...item,name:'Tên mới',version:3});renderForm();const user=userEvent.setup({delay:null});const name=await screen.findByDisplayValue(item.name);await user.clear(name);await user.type(name,'  Tên mới  ');fireEvent.click(screen.getByRole('button',{name:/Lưu/}));await waitFor(()=>expect(api.updateCraftVillage).toHaveBeenCalled());expect(api.updateCraftVillage.mock.calls[0][1]).toEqual(expect.objectContaining({name:'Tên mới',version:2,mediaId:'media-1'}));});
  it('adds and reorders descriptions and highlights',async()=>{renderForm();const user=userEvent.setup({delay:null});await screen.findByDisplayValue(item.name);await user.click(screen.getByRole('button',{name:/Thêm đoạn/}));const paragraph=screen.getByText('Đoạn 2').closest('.ant-form-item')?.querySelector('textarea');if(!paragraph)throw new Error('Không tìm thấy đoạn');fireEvent.change(paragraph,{target:{value:'Đoạn mới'}});await user.click(screen.getAllByRole('button',{name:'Đưa đoạn lên'})[1]);await user.click(screen.getByRole('button',{name:/Thêm điểm nổi bật/}));const highlight=screen.getByText('Điểm 2').closest('.ant-form-item')?.querySelector('input');if(!highlight)throw new Error('Không tìm thấy điểm');fireEvent.change(highlight,{target:{value:'Điểm mới'}});await user.click(screen.getAllByRole('button',{name:'Đưa điểm nổi bật lên'})[1]);expect(screen.getByDisplayValue('Đoạn mới')).toBeInTheDocument();expect(screen.getByDisplayValue('Điểm mới')).toBeInTheDocument();});
  it('previews form values without a public API call',async()=>{renderForm();const user=userEvent.setup({delay:null});const name=await screen.findByDisplayValue(item.name);await user.clear(name);await user.type(name,'Tên xem trước');fireEvent.click(screen.getByRole('button',{name:/Xem trước/}));expect(await screen.findByRole('heading',{name:'Tên xem trước'})).toBeInTheDocument();expect(api.fetchCraftVillage).toHaveBeenCalledTimes(1);expect(api.updateCraftVillage).not.toHaveBeenCalled();});
  it('keeps input and locks save after conflict',async()=>{api.updateCraftVillage.mockRejectedValue(new ApiError({code:'CRAFT_VILLAGE_VERSION_CONFLICT',message:'Dữ liệu đã thay đổi'},undefined,409));renderForm();const user=userEvent.setup({delay:null});const name=await screen.findByDisplayValue(item.name);await user.clear(name);await user.type(name,'Tên chưa bị ghi đè');fireEvent.click(screen.getByRole('button',{name:/Lưu/}));expect(await screen.findByText('Dữ liệu đã được người khác cập nhật')).toBeInTheDocument();expect(screen.getByDisplayValue('Tên chưa bị ghi đè')).toBeInTheDocument();expect(screen.getByRole('button',{name:/Lưu/})).toBeDisabled();});
});
