import { ArrowDownOutlined,ArrowLeftOutlined,ArrowUpOutlined,DeleteOutlined,EyeOutlined,PlusOutlined,ReloadOutlined,SaveOutlined } from '@ant-design/icons';
import { zodResolver } from '@hookform/resolvers/zod';
import { useMutation,useQuery,useQueryClient } from '@tanstack/react-query';
import { Alert,Button,Card,Col,Form,Input,InputNumber,Modal,Row,Select,Skeleton,Space,Switch,Typography,message } from 'antd';
import type { JSX } from 'react'; import { useEffect,useState } from 'react'; import { Controller,useFieldArray,useForm } from 'react-hook-form'; import { useNavigate,useParams } from 'react-router-dom';
import { createCraftVillage,fetchCraftVillage,updateCraftVillage } from '../../../api/craft-villages';
import { useAuthStore } from '../../../store/auth-store'; import { useUnsavedChangesStore } from '../../../store/unsaved-changes-store'; import { ApiError } from '../../../types/api'; import { CRAFT_VILLAGE_CATEGORIES } from '../../../types/craft-village';
import { ImageUploadField } from '../about/ImageUploadField'; import { describeCraftVillageError } from './craft-village-errors';
import { craftVillageFormSchema,craftVillageToForm,EMPTY_CRAFT_VILLAGE_FORM,formToCraftVillagePayload,type CraftVillageFormValues } from './craft-village.schema'; import { CraftVillagePreviewDrawer } from './CraftVillagePreviewDrawer'; import './craft-villages.css';

export function CraftVillageFormPage():JSX.Element {
  const { id }=useParams<{id:string}>(); const isCreate=!id||id==='new'; const navigate=useNavigate(); const queryClient=useQueryClient(); const canManage=useAuthStore((state)=>state.user?.role==='ADMIN'); const setGlobalDirty=useUnsavedChangesStore((state)=>state.setDirty);
  const [previewOpen,setPreviewOpen]=useState(false); const [conflict,setConflict]=useState(false);
  const villageQuery=useQuery({ queryKey:['admin-craft-village',id],queryFn:({signal})=>fetchCraftVillage(id!,signal),enabled:!isCreate });
  const { control,handleSubmit,reset,setValue,watch,formState:{errors,isDirty} }=useForm<CraftVillageFormValues>({ resolver:zodResolver(craftVillageFormSchema),defaultValues:EMPTY_CRAFT_VILLAGE_FORM });
  const descriptions=useFieldArray({ control,name:'descriptions',keyName:'fieldKey' }); const highlights=useFieldArray({ control,name:'highlights',keyName:'fieldKey' }); const values=watch();
  useEffect(()=>{ if(villageQuery.data)reset(craftVillageToForm(villageQuery.data)); },[villageQuery.data,reset]);
  useEffect(()=>{ setGlobalDirty(canManage&&isDirty,'Bạn có thay đổi chưa lưu ở Làng nghề. Rời khỏi trang sẽ mất các thay đổi này.'); },[canManage,isDirty,setGlobalDirty]);
  useEffect(()=>()=>useUnsavedChangesStore.getState().setDirty(false),[]);
  const saveMutation=useMutation({ mutationFn:(form:CraftVillageFormValues)=>{ const payload=formToCraftVillagePayload(form); return isCreate?createCraftVillage(payload):updateCraftVillage(id!,{...payload,version:villageQuery.data!.version}); },
    onSuccess:(saved)=>{ reset(craftVillageToForm(saved));setConflict(false);void queryClient.invalidateQueries({queryKey:['admin-craft-villages']});void queryClient.invalidateQueries({queryKey:['admin-craft-village',saved.id]});message.success(isCreate?'Đã tạo làng nghề':'Đã lưu thay đổi');navigate(`/content/craft-villages/${saved.id}`,{replace:true}); },
    onError:(error:unknown)=>{ if(error instanceof ApiError&&error.status===409&&error.code==='CRAFT_VILLAGE_VERSION_CONFLICT')setConflict(true);message.error(describeCraftVillageError(error)); } });
  function cancel():void { const leave=()=>{setGlobalDirty(false);navigate('/content/craft-villages');};if(!isDirty||!canManage)return leave();Modal.confirm({title:'Hủy thay đổi?',content:'Các nội dung chưa lưu sẽ bị mất.',okText:'Rời trang',cancelText:'Ở lại',okButtonProps:{danger:true},onOk:leave}); }
  async function loadLatest():Promise<void>{const result=await villageQuery.refetch();if(result.data){reset(craftVillageToForm(result.data));setConflict(false);message.info('Đã tải phiên bản mới nhất');}}
  if(isCreate&&!canManage)return <Alert type="error" showIcon message="Bạn không có quyền tạo làng nghề" action={<Button onClick={()=>navigate('/content/craft-villages')}>Về danh sách</Button>}/>;
  if(!isCreate&&villageQuery.isLoading)return <Skeleton active paragraph={{rows:14}}/>;
  if(!isCreate&&villageQuery.isError)return <Alert type="error" showIcon message="Không tải được làng nghề" description={describeCraftVillageError(villageQuery.error)} action={<Button icon={<ReloadOutlined/>} onClick={()=>void villageQuery.refetch()}>Thử lại</Button>}/>;
  const disabled=!canManage||saveMutation.isPending;
  return <div className="craft-village-form-page"><div className="craft-village-form-page__header"><div><Button type="text" htmlType="button" icon={<ArrowLeftOutlined/>} onClick={cancel}>Danh sách</Button><Typography.Title level={3}>{isCreate?'Thêm làng nghề mới':`${canManage?'Chỉnh sửa':'Chi tiết'} ${villageQuery.data?.name??''}`}</Typography.Title></div>
    <Space wrap><Button htmlType="button" icon={<EyeOutlined/>} onClick={()=>setPreviewOpen(true)}>Xem trước</Button><Button htmlType="button" onClick={cancel}>{canManage?'Hủy':'Đóng'}</Button>{canManage&&<Button type="primary" htmlType="button" icon={<SaveOutlined/>} loading={saveMutation.isPending} disabled={conflict||saveMutation.isPending||(!isCreate&&!isDirty)} onClick={()=>void handleSubmit((form)=>saveMutation.mutate(form))()}>Lưu</Button>}</Space></div>
    {!canManage&&<Alert type="info" showIcon message="Bạn đang xem ở chế độ chỉ đọc"/>}{conflict&&<Alert type="warning" showIcon message="Dữ liệu đã được người khác cập nhật" description="Nội dung bạn đang nhập vẫn được giữ trên form. Hãy tải phiên bản mới nhất trước khi tiếp tục lưu." action={<Button size="small" onClick={()=>void loadLatest()}>Tải phiên bản mới nhất</Button>}/>}
    <form className="craft-village-form-page__form" onSubmit={(event)=>event.preventDefault()}><Card title="Thông tin cơ bản"><Row gutter={16}>
      <Col xs={24} lg={16}><Controller name="name" control={control} render={({field})=><Form.Item label="Tên làng nghề" required validateStatus={errors.name?'error':undefined} help={errors.name?.message}><Input {...field} disabled={disabled} maxLength={150} showCount/></Form.Item>}/></Col>
      <Col xs={24} lg={8}><Controller name="category" control={control} render={({field})=><Form.Item label="Danh mục" required validateStatus={errors.category?'error':undefined} help={errors.category?.message}><Select {...field} disabled={disabled} options={CRAFT_VILLAGE_CATEGORIES.map((value)=>({value,label:value}))}/></Form.Item>}/></Col></Row>
      <Controller name="address" control={control} render={({field})=><Form.Item label="Địa chỉ" required validateStatus={errors.address?'error':undefined} help={errors.address?.message}><Input {...field} disabled={disabled} maxLength={255} showCount/></Form.Item>}/>
      <Row gutter={16}><Col xs={24} lg={12}><Controller name="workingTime" control={control} render={({field})=><Form.Item label="Thời gian hoạt động" required validateStatus={errors.workingTime?'error':undefined} help={errors.workingTime?.message}><Input {...field} disabled={disabled} maxLength={100} placeholder="VD: 08:00 - 17:00 hằng ngày"/></Form.Item>}/></Col>
      <Col xs={24} lg={12}><Controller name="mainProducts" control={control} render={({field})=><Form.Item label="Sản phẩm chính" required validateStatus={errors.mainProducts?'error':undefined} help={errors.mainProducts?.message}><Input {...field} disabled={disabled} maxLength={255} showCount/></Form.Item>}/></Col></Row>
      <Row gutter={16}><Col xs={12} lg={4}><Controller name="sortOrder" control={control} render={({field})=><Form.Item label="Thứ tự"><InputNumber {...field} disabled={disabled} min={0} precision={0} style={{width:'100%'}}/></Form.Item>}/></Col><Col xs={12} lg={8}><Controller name="isActive" control={control} render={({field})=><Form.Item label="Hiển thị trên Mini App"><Switch checked={field.value} disabled={disabled} onChange={field.onChange}/></Form.Item>}/></Col></Row>
      <Controller name="summary" control={control} render={({field})=><Form.Item label="Mô tả ngắn" required validateStatus={errors.summary?'error':undefined} help={errors.summary?.message}><Input.TextArea {...field} disabled={disabled} rows={3} maxLength={300} showCount/></Form.Item>}/></Card>
    <Card title="Ảnh đại diện"><ImageUploadField label="ảnh đại diện" imageUrl={values.imageUrl??undefined} alt={values.imageAlt} disabled={disabled} errorMessage={errors.imageUrl?.message} errorId="craft-village-image-error" hint="JPEG, PNG hoặc WebP; backend tự tối ưu sang WebP." onUploaded={({mediaId,imageUrl})=>{setValue('mediaId',mediaId,{shouldDirty:true,shouldValidate:true});setValue('imageUrl',imageUrl,{shouldDirty:true,shouldValidate:true});}} onRemove={()=>{setValue('mediaId',null,{shouldDirty:true,shouldValidate:true});setValue('imageUrl',null,{shouldDirty:true,shouldValidate:true});}}/><Controller name="imageAlt" control={control} render={({field})=><Form.Item label="Mô tả ảnh" validateStatus={errors.imageAlt?'error':undefined} help={errors.imageAlt?.message}><Input {...field} disabled={disabled} maxLength={150} showCount/></Form.Item>}/></Card>
    <Card title="Mô tả chi tiết" extra={canManage&&<Button htmlType="button" icon={<PlusOutlined/>} disabled={descriptions.fields.length>=20||disabled} onClick={()=>descriptions.append({text:''})}>Thêm đoạn</Button>}>{errors.descriptions?.root?.message&&<Alert type="error" message={errors.descriptions.root.message}/>} {descriptions.fields.map((item,index)=><div className="craft-village-form-page__dynamic-row" key={item.fieldKey}><Controller name={`descriptions.${index}.text`} control={control} render={({field})=><Form.Item label={`Đoạn ${index+1}`} validateStatus={errors.descriptions?.[index]?.text?'error':undefined} help={errors.descriptions?.[index]?.text?.message} style={{flex:1}}><Input.TextArea {...field} disabled={disabled} rows={4} maxLength={5000} showCount/></Form.Item>}/>{canManage&&<Space orientation="vertical"><Button htmlType="button" icon={<ArrowUpOutlined/>} aria-label="Đưa đoạn lên" disabled={index===0||disabled} onClick={()=>descriptions.move(index,index-1)}/><Button htmlType="button" icon={<ArrowDownOutlined/>} aria-label="Đưa đoạn xuống" disabled={index===descriptions.fields.length-1||disabled} onClick={()=>descriptions.move(index,index+1)}/><Button htmlType="button" danger icon={<DeleteOutlined/>} aria-label="Xóa đoạn" disabled={descriptions.fields.length===1||disabled} onClick={()=>descriptions.remove(index)}/></Space>}</div>)}</Card>
    <Card title="Điểm nổi bật" extra={canManage&&<Button htmlType="button" icon={<PlusOutlined/>} disabled={highlights.fields.length>=20||disabled} onClick={()=>highlights.append({text:''})}>Thêm điểm nổi bật</Button>}>{!highlights.fields.length&&<Typography.Text type="secondary">Chưa có điểm nổi bật.</Typography.Text>}{highlights.fields.map((item,index)=><div className="craft-village-form-page__dynamic-row" key={item.fieldKey}><Controller name={`highlights.${index}.text`} control={control} render={({field})=><Form.Item label={`Điểm ${index+1}`} validateStatus={errors.highlights?.[index]?.text?'error':undefined} help={errors.highlights?.[index]?.text?.message} style={{flex:1}}><Input {...field} disabled={disabled} maxLength={200} showCount/></Form.Item>}/>{canManage&&<Space><Button htmlType="button" icon={<ArrowUpOutlined/>} aria-label="Đưa điểm nổi bật lên" disabled={index===0||disabled} onClick={()=>highlights.move(index,index-1)}/><Button htmlType="button" icon={<ArrowDownOutlined/>} aria-label="Đưa điểm nổi bật xuống" disabled={index===highlights.fields.length-1||disabled} onClick={()=>highlights.move(index,index+1)}/><Button htmlType="button" danger icon={<DeleteOutlined/>} aria-label="Xóa điểm nổi bật" disabled={disabled} onClick={()=>highlights.remove(index)}/></Space>}</div>)}</Card>
    <Card title="Ghi chú cho khách tham quan"><Controller name="visitorNote" control={control} render={({field})=><Form.Item validateStatus={errors.visitorNote?'error':undefined} help={errors.visitorNote?.message}><Input.TextArea {...field} disabled={disabled} rows={5} maxLength={2000} showCount/></Form.Item>}/></Card></form>
    <CraftVillagePreviewDrawer open={previewOpen} values={values} onClose={()=>setPreviewOpen(false)}/></div>;
}
